name: 'ttyd ci'

on:
  push:
    branches:
      - 'main'
      - 'release/**'
  pull_request:
    branches:
      - 'main'
      - 'release/**'

permissions:
  checks: 'write'
  contents: 'read'
  statuses: 'write'

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target: [i686, x86_64, arm, armhf, aarch64, mips, mipsel, mips64, mips64el, ppc64, ppc64le, s390x, win32]
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config \
            libwebsockets-dev libjson-c-dev libuv1-dev libcmocka-dev zlib1g-dev libssl-dev
      - name: Build 
        env:
          BUILD_TARGET: ${{ matrix.target }}
        run: ./scripts/cross-build.sh
      - name: Run tests
        run: ./scripts/run-test.sh

